name: Build static Ruby
on: [push]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Build base image
              run: bazel build //base:image
            - name: Build image
              run: docker build -t test .